version: 0.2

phases:
  install:
    commands:
      - echo Installing Mocha...
      - npm install -g mocha
      - echo Installing docker y docker-compose...
      - npm install -g docker docker-compose
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm i
  build:
    commands:
      - echo Build started on `date`
 ##     - echo mocha test
##      - mocha test.js
      - echo Compiling the Node.js code
      - node app.js
      - echo Start and build docker-compose
      - docker-compose build
  post_build:
    commands:
      - echo levanta docker compose docker-compose up
      - docker-compose up
artifacts:
  files:
    - app.js